bonus:
    adapter: Dahius_VirtualPos_Adapter_CC5
    parameters:
        host:
            bank: https://ccpos.garanti.com.tr/servlet/cc5ApiServer
            authentication: https://ccpos.garanti.com.tr/servlet/gar3Dgate
            callback: https://example.com/callback/for/3DSecure
        username: garanti_user
        password: garanti_pass
        store_type: 3d
        working_mode: P
        client_id: 12345678
        store_key: 123456
        valid_md_status: [1, 2, 3, 4]

axess:
    adapter: Dahius_VirtualPos_Adapter_CC5
    parameters:
        host:
            bank: https://www.sanalakpos.com/servlet/cc5ApiServer
            authentication: https://www.sanalakpos.com/servlet/est3Dgate
            callback: https://example.com/callback/for/3DSecure
        username: akbank_user
        password: akbank_pass
        store_type: 3d
        working_mode: P
        client_id: 12345678
        store_key: 123456
        valid_md_status: [1, 2, 3, 4]

cardfinans:
    adapter: Dahius_VirtualPos_Adapter_CC5
    parameters:
        host:
            bank: https://www.fbwebpos.com/servlet/cc5ApiServer
            authentication: https://www.fbwebpos.com/servlet/ThreeDGate
            callback: https://example.com/callback/for/3DSecure
        username: finans_user
        password: finans_pass
        store_type: 3d
        working_mode: P
        client_id: 12345678
        store_key: 123456
        valid_md_status: [1, 2, 3, 4]
    
advantage:
    adapter: Dahius_VirtualPos_Adapter_CC5
    parameters:
        host:
            bank: https://vpos.advantage.com.tr/servlet/cc5ApiServer
            authentication: https://vpos.advantage.com.tr/servlet/hsbc3Dgate
            callback: https://example.com/callback/for/3DSecure
        username: hsbc_user
        password: hsbc_pass
        store_type: 3d
        working_mode: P
        client_id: 12345678
        store_key: 123456
        valid_md_status: [1, 2, 3, 4]
    
maximum:
    adapter: Dahius_VirtualPos_Adapter_CC5
    parameters:
        host:
            bank: https://spos.isbank.com.tr/servlet/cc5ApiServer
            authentication: https://spos.isbank.com.tr/servlet/est3Dgate
            callback: https://example.com/callback/for/3DSecure
        username: maximum_user
        password: maximum_pass
        store_type: 3d
        working_mode: P
        client_id: 12345678
        store_key: 123456
        valid_md_status: [1, 2, 3, 4]
    
worldcard:
    adapter: Dahius_VirtualPos_Adapter_Posnet
    parameters:
        host:
            bank: https://www.posnet.ykb.com/PosnetWebService/XML
            authentication: https://www.posnet.ykb.com/PosnetWebService/XML
            authorization: https://www.posnet.ykb.com/3DSWebService/YKBPaymentService
            callback: https://example.com/callback/for/3DSecure
        username: ykb_user
        password: ykb_pass
        tif: 12345678
        mid: 1234567890
        posnet_id: 123
        merchant_key: 310,28,192,97,13,90,45,167
        valid_md_status: [1, 2, 3, 4]
